---
name: test-bats

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.1

    - name: Mod Download
      run: |
        set -e

        if [ -n "$GITHUB_RUN_ID" ]; then
            export GITHUB_API_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        fi
        
        go mod download

    - name: Setup BATS
      run: |
        set -e

        if [ -n "$GITHUB_RUN_ID" ]; then
            export GITHUB_API_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        fi

        git clone https://github.com/bats-core/bats-core.git && bats-core/install.sh $HOME
    
    - name: Run tests
      run: bats test/bats

    # - name: Test
    #   run: go test -v ./...